Repository ucsb-cs156-w22/team04-w22-5pm-courses, pull requests merged in 2022-03, with the labels that each got.

#31 ap - add loadsubjects placeholder page
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminLoadSubjectsPage.js
  frontend/src/stories/pages/AdminLoadSubjectsPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/AdminLoadSubjectsPage.test.js
Labels: w22-5pm-2

#40 Add Developer API to UCSBSubjects
  .env.SAMPLE
  src/main/java/edu/ucsb/cs156/example/controllers/UCSBSubjectsController.java
  src/main/java/edu/ucsb/cs156/example/services/UCSBSubjectsService.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/example/services/UCSBSubjectsServiceTests.java
Labels: w22-5pm-1

#42 Team1 UCSBCurriculum Backend
  src/main/java/edu/ucsb/cs156/example/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/example/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/example/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/example/services/UCSBCurriculumServiceTests.java
Labels: w22-5pm-1, ATTN: Merge conflicts

#45 Team02 - PersonalSchedule Table Components
  frontend/src/fixtures/personalScheduleFixtures.js
  frontend/src/main/components/PersonalSchedules/PersonalSchedulesTable.js
  frontend/src/main/utils/PersonalScheduleUtils.js
  frontend/src/stories/components/PersonalSchedules/PersonalSchedulesTable.stories.js
  frontend/src/tests/components/PersonalSchedules/PersonalSchedulesTable.test.js
  frontend/src/tests/utils/PersonalScheduleUtils.test.js
Labels: w22-5pm-2, Merge-Candidate

#46 W22-5pm-2 Personal Schedule Form Component
  frontend/src/fixtures/personalSchedulesFixtures.js
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/stories/components/PersonalSchedules/PersonalScheduleForm.stories.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
Labels: w22-5pm-2, Merge-Candidate

#33 alex - Admin Personal Schedule Placeholder Page and Navbar
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminPersonalSchedulePage.js
  frontend/src/stories/pages/AdminPersonalSchedulePage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/AdminPersonalSchedulePage.test.js
Labels: w22-5pm-2

#35 Personal Schedules Place Holders
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesIndexPage.js
  frontend/src/stories/pages/HomePage/PersonalSchedules/PersonalSchedulesCreatePage.stories.js
  frontend/src/stories/pages/HomePage/PersonalSchedules/PersonalSchedulesEditPage.stories.js
  frontend/src/stories/pages/HomePage/PersonalSchedules/PersonalSchedulesIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
Labels: w22-5pm-2

#39 W22 5pm 2 zw,ap - add personal schedule endpoints get and post
  src/main/java/edu/ucsb/cs156/example/controllers/PersonalSchedulesController.java
  src/main/java/edu/ucsb/cs156/example/entities/PersonalSchedule.java
  src/main/java/edu/ucsb/cs156/example/repositories/PersonalScheduleRepository.java
  src/test/java/edu/ucsb/cs156/example/controllers/PersonalSchedulesControllerTests.java
Labels: w22-5pm-2

#48 W22 5pm 2 sg add subj table
  frontend/src/fixtures/ucsbSubjectsFixtures.js
  frontend/src/main/components/UCSBSubjects/UCSBSubjectsTable.js
  frontend/src/main/pages/AdminLoadSubjectsPage.js
  frontend/src/main/utils/UCSBSubjectUtils.js
  frontend/src/stories/components/UCSBSubjects/UCSBSubjectsTable.stories.js
  frontend/src/tests/components/UCSBSubjects/UCSBSubjectsTable.test.js
  frontend/src/tests/utils/UCSBSubjectUtils.test.js
Labels: w22-5pm-2, Merge-Candidate

#52 sg-changed quarter to QYY on PerSchedTable
  frontend/src/main/components/PersonalSchedules/PersonalSchedulesTable.js
Labels: w22-5pm-2, Merge-Candidate

#58 Add table component to display lecture information
  frontend/src/fixtures/courseFixtures.js
  frontend/src/main/components/Courses/BasicCourseTable.js
  frontend/src/stories/components/Courses/BasicCourseTable.stories.js
  frontend/src/tests/components/Courses/BasicCourseTable.test.js
Labels: w22-5pm-1

#60 Fix deleted files issue, component for BasicSearchForm
  frontend/package-lock.json
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/components/Subjects/SingleSubjectDropdown.js
  frontend/src/main/pages/AdminLoadSubjectsPage.js
  frontend/src/main/pages/HomePage.js
  frontend/src/stories/components/BasicCourseSearch/BasicCourseSearchForm.stories.js
  frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  frontend/src/tests/components/Levels/SingleLevelDropdown.test.js
  frontend/src/tests/components/Quarters/SingleQuarterDropdown.test.js
  frontend/src/tests/components/Subjects/SingleSubjectDropdown.test.js
Labels: w22-5pm-1

#47 W22 5pm 2 Sg/Al: Implement Load Subjects Button
  frontend/src/main/components/UCSBSubjects/UCSBSubjectsTable.js
  frontend/src/main/pages/AdminLoadSubjectsPage.js
  frontend/src/main/utils/UCSBSubjectUtils.js
  frontend/src/tests/pages/AdminLoadSubjectsPage.test.js
Labels: w22-5pm-2

#59 W22 5pm 2 zw,ap - add put and delete endpoints for personalschedules
  src/main/java/edu/ucsb/cs156/example/controllers/PersonalSchedulesController.java
  src/test/java/edu/ucsb/cs156/example/controllers/PersonalSchedulesControllerTests.java
Labels: w22-5pm-2, Merge-Candidate

#74 W22 5pm 1 tableonsearch
  .github/workflows/02-frontend-03-mutation-testing.yml
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  frontend/src/tests/pages/HomePage.test.js
  src/main/java/edu/ucsb/cs156/example/controllers/UCSBSubjectsController.java
  src/test/java/edu/ucsb/cs156/example/controllers/UCSBSubjectsControllerTests.java
Labels: w22-5pm-1

#67 W22 5pm 2 - Add Personal Schedule List - Index Page
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesIndexPage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
Labels: w22-5pm-2

#71 rj - Personal Schedules Create Page
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
Labels: w22-5pm-2, 10
